### ISSUE TITLE
Error interrupts diagnostic message from compile command

### ISSUE THREAD

**Issue by wti** [tayloraswift/swift-unidoc#332]
It seems when a package has a dependency but no documentation links to it, the compile command diagnostic listing unused package is interrupted by an error.

It's thrown from extension `DigraphExplorer.Nodes.callAsFunction(Node.ID)` when the node is undefined (likely b/c unused).  The `ModuleGraph` initialization is trying to flatten the nodes as part of emitting the warning.

I'll attach a separate file to reproduce the issue.

I'm not sure this is a proper/relevant usage, but in my own small sampling I seem to have more than one offender.

**Comment by wti** [comment]
Attached is a bash script that generates a package, clears a workspace, and runs `unidoc compile` to demonstrate the error.  Put it in some peer directory of swift-unidoc after you've done a debug build.

Reproduced in current main/master HEAD 48b03c291b249db097b9d6d62c9258aa2175e2a2.


[errorListingUnusedPackagesWhenCompiling.sh.txt](https://github.com/user-attachments/files/16971546/errorListingUnusedPackagesWhenCompiling.sh.txt)

**Comment by tayloraswift** [comment]
this was happening because you were using a case-sensitive project folder name (`DocGen`), which normalizes to `docgen` under SwiftPM’s package identifier rules. unidoc was incorrectly using the canonical name to compute a file path using the all-lowercase name, which it then fails to find on case-sensitive file systems. 

#335 should fix this problem

**Comment by wti** [comment]
Thanks for the quick response - that sounds both plausible and annoying to have to flow both forms through data paths.

But after pulling/cleaning/running, I still get the same problem.  In case it helps, I attached screenshots of xcode debug context.  In this series, frame 1 expects the index lookup to succeed, but it doesn't in Frame 0, likely b/c logging has never been used/put in the graph.  I included ~10 frames mainly to show the empty graph.

Again, this is from the degenerate case of no documentation on a rare usage path, so I understand it's not a priority.  It's mainly in case it helps you.  I confused myself thinking through the implicit calls throught consuming layers, so I'm giving up for now. 

[uderr.zip](https://github.com/user-attachments/files/16986019/uderr.zip)

**Comment by tayloraswift** [comment]
the code that you’re looking at is a generic graph traversal algorithm not specific to Swift documentation, and i doubt that is what’s causing the issue. instead, i think there is a mistake in your `unidoc compile` invocation here:

```
swift build --configuration debug \
    --package-path /swift/DocGap/DocGap \
    --scratch-path /swift/DocGap/DocGap/.build.ssgc \
    -Xswiftc -emit-symbol-graph \
    -Xswiftc -emit-symbol-graph-dir \
    -Xswiftc /swift/DocGap/DocGap/.build.ssgc/ssgc \
    -Xswiftc -symbol-graph-minimum-access-level \
    -Xswiftc internal \
    -Xswiftc -emit-extension-block-symbols \
    -Xswiftc -include-spi-symbols \
    -Xswiftc -skip-inherited-docs
```

the dummy package you create is not located at `$PREFIX/DocGap/DocGap`, but rather at `$PREFIX/DocGap`. unfortunately you didn’t get a very helpful diagnostic because SwiftPM tries to be “too helpful” and walks up the path hierarchy until it finds a `Package.swift` manifest file. but the rest of the build system is unaware of SwiftPM’s workspace annealing, so you get an empty symbol graph, as Unidoc can’t find the sources.

i think it makes sense for us to check specifically that the manifests live at the expected locations, so i’ve created a new issue #337

**Comment by tayloraswift** [comment]
did you by accident pass the path to the SwiftPM project directory to `--search-path`, instead of the *parent* directory?

**Comment by wti** [comment]
Pilot error confirmed!  (Not by accident but by confused decision)  Sorry for the noise.
